--Changeset kumargautam:Default Privileges
INSERT INTO privilege JSON '{"id":"5bb71fc82ff9a91aa88ebee1_ADMIN_READ_WRITE","name":"ADMIN_READ_WRITE"}';
INSERT INTO privilege JSON '{"name":"ADMIN_READ","id":"5bb71fc82ff9a91aa88ebee1_ADMIN_READ"}';
INSERT INTO privilege JSON '{"name":"USER_READ_WRITE","id":"5bb71fc82ff9a91aa88ebee1_USER_READ_WRITE"}';
INSERT INTO privilege JSON '{"name":"READONLY","id":"5bb71fc82ff9a91aa88ebee1_READONLY"}';